# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            esio
tagline:          esio
description:      ""
url:              https://esio.one.pl
baseurl:          /

author:
  name:           'Grzegorz Eliszewski'
  url:            https://esio.one.pl

paginate:         1