markdown:    redcarpet
highlighter: pygments

# theme: ace-theme

permalink: /posts/:year/:month/:title

title: esio homepage
url: http://esio.one.pl
#baseurl: /
description: esio homepage

plugins: [jekyll-paginate]
paginate: 5
paginate_path: '/:num'

exclude: [Gemfile, Gemfile.lock, gulpfile.js, package.json, node_modules, css, scripts]
